### ISSUE TITLE
ambari_wait status:

### ISSUE THREAD

**Issue by promiseowolabi** [Chaffelson/whoville#6]
The deployment fails at this stage:

`Waiting for 90s before deploying cluster with services: AMBARI_METRICS HDFS MAPREDUCE2 YARN ZOOKEEPER DRUID STREAMLINE NIFI KAFKA STORM REGISTRY HBASE PHOENIX ZEPPELIN SOLR
Deploying the cluster once 1 hosts are registered.

/tmp/ambari-bootstrap-master/deploy/deploy-recommended-cluster.bash: line 77: hosts_regd[*]: unbound variable
Now open your browser to http://217.70.211.17:8080 and login as admin/StrongPassword to observe the cluster install
Waiting for cluster to be installed...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 2, in <module>
IndexError: list index out of range
ambari_wait status:
ambari_wait status:
ambari_wait status:
ambari_wait status:
^C
[root@hdp11 ~]#
`

**Comment by Chaffelson** [comment]
Hi @promiseowolabi I am sorry but I have only just seen this Issue report as the notifications on this repo were somehow disabled. I believe this issue was fixed in one of the forks which I have just pulled up to date in this version of the repo.
I am sure you've probably moved on from this by now, but my apologies again for missing your request for assistance.

**Comment by promiseowolabi** [comment]
Thanks Dan, I will try again.

**Comment by Chaffelson** [comment]
No update on this in a while, so I'm going to close it pending further requirements. Thanks!
